# Generated by Django 4.2.11 on 2024-05-04 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_combination",
        ),
        migrations.RenameField(
            model_name="film",
            old_name="director",
            new_name="director_id",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="value",
            new_name="rating",
        ),
        migrations.RemoveField(
            model_name="review",
            name="film",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AddField(
            model_name="review",
            name="film_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="users.film",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="director",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user_id", "film_id"), name="unique_combination"
            ),
        ),
    ]
