name: django-test

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Run django tests
        run: |
          python manage.py test --pattern="tests/test_django*.py"

      - name: Run end-to-end tests
        run: |
          python manage.py test --pattern="tests/test_e2e.py"
