name: django-test

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: psf/black@stable
        with:
          options: "--check ."

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Run django tests
        run: |
          python manage.py test --pattern="../tests/test_django_*.py"

      - name: Run end-to-end tests
        run: |
          python manage.py test --pattern="../tests/test_e2e.py"
