name: django-test

on:
  push:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Create virtualenv
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Run django tests
        working-directory: ./src/backend
        run: |
          pip install -r ../../requirements.txt
          python manage.py test apps.users.test_models
          python manage.py test apps.users.test_urls
          python manage.py test apps.users.test_views

          # We don't run end to end because it requires a running server
