name: django-test

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Run django tests
        run: |
          cd src/backend
          python manage.py test apps.users.test_models
          python manage.py test apps.users.test_urls
          python manage.py test apps.users.test_views

      - name: Run end-to-end tests
        run: |
          cd src/backend
          python manage.py test apps.users.test_end_to_end
